spring:
   application:
      name: client-feign
   cloud:
      nacos:
         discovery:
            server-addr: 127.0.0.1:8848
   zipkin:
      base-url: http://127.0.0.1:9411 
server:
   port: 80
#eureka:
#   client:
#      serviceUrl:
#         defaultZone: http://localhost:8000/eureka/
#   instance:
feign:
   httpclient:
      enable: true
   okhttp:
      enable: false
ribbon:
#更改负载策略，本地优先
   eureka:
      enable: false
   eager-load:
      enabled: true
      clients: service-provider,service-provider2
   ConnectTimeout: 5000
   ReadTimeout: 5000
service-provider:
   ribbon:
      NFLoadBalancerRuleClassName: test.consumer.MyLocalPriorityRule
service-provider2:
   ribbon:
      NFLoadBalancerRuleClassName: test.consumer.MyLocalPriorityRule
serverIP: 192.168.2.126
hystrix:
   command:
      default:
         execution:
            thread:
               timeoutInMilliseconds: 5000