spring:
   application:
      name: service-provider
   datasource:
      url: jdbc:mysql://127.0.0.1:3306/kz?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      username: root
      password: Ee84336462!
      driver-class-name: com.mysql.cj.jdbc.Driver
   cloud:
      nacos:
         discovery:
            server-addr: 127.0.0.1:8848
   zipkin:
      base-url: http://127.0.0.1:9411
   sleuth:
      sampler:
         percentage: 1.0
server:
   port: 8001
#eureka:
#   client:
#      serviceUrl:
#         defaultZone: http://localhost:8000/eureka/
#   instance:
#      instance-id: service-provider-8001
#      prefer-ip-address: true
ribbon:
   eager-load:
      enabled: true
      clients: service-provider2
   eureka:
      enable: false
   ConnectTimeout: 5000
   ReadTimeout: 5000
feign:
   httpclient:
      enable: true
   okhttp:
      enable: false
seata:
   enabled: true
   application-id: ${spring.application.name}
   tx-service-group: test_tx_group
   enable-auto-data-source-proxy: true
   config:
      type: nacos
      nacos:
         serverAddr: 127.0.0.1:8848
         group: SEATA_GROUP
   registry:
      type: nacos
      nacos:
         application: seata
         server-addr: 127.0.0.1:8848
         group: SEATA_GROUP